<?php
// module/Album/view/album/album/delete.phtml:

$title = 'Delete album';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<br/>
Do you really want to delete album <b> <?php echo $album->title.'</b> by <b>'.$album->artist; ?>? 
    
<?php $url = $this->url( 'album', array( 'action'=>'delete', 'id'=>$id )); ?>    

<form action='<?php echo $url; ?>' method='post' name=''>
    <input type='hidden' value='<?php echo $id; ?>' name='id' />
    <input type='submit' value='Yes' name='del' />
    <input type='submit' value='No'  name='del' />
    </form>
    